### ISSUE TITLE
Ability to serve static files

### ISSUE THREAD

**Issue by garrettheel** [lyft/envoy#378]
It would be great to have the ability to serve static files from Envoy. 

My use-case is to serve static files for an HTML frontend (HTML, JS, CSS, etc.), which should be a fairly common one. Right now you would have to put something like nginx in the middle to efficiently do this.

**Comment by rshriram** [comment]
@garrettheel would this end up turning Envoy into full fledged web server? Because, we would now have to take care of file encodings, gzip stuff, cache headers, and so on. Just afraid of code complexity/bloat.

**Comment by mattklein123** [comment]
This would only ever be added as a standalone filter, but overall I agree with @rshriram that we are unlikely to add this into the core server. But will leave open just for tracking purposes.

**Comment by bgaff** [comment]
Why not add fastcgi as a filter? Seems like a win-win.

**Comment by skippy** [comment]
@mattklein123, what I was hoping for was a way to serve static files on certain non-2xx responses, such as a 500 or 403.  So rather than returning the envoy default msg, it could return a file.  

something along the lines of haproxy's `  errorfile 403 /etc/haproxy/403.json`

is something like that doable?

**Comment by mattklein123** [comment]
@skippy it's definitely doable and I'm not opposed, but someone would need to do a proper design and implement.

**Comment by skippy** [comment]
@mattklein123 if you are ok with it, I'll make a separate issue to design and track static files for error handling... that is a much more specific use-case than general static files (I agree with your comments on that score).  

but in the meanwhile, time to dust off haproxy so I can serve error files :)

**Comment by mattklein123** [comment]
> if you are ok with it, I'll make a separate issue to design and track static files for error handling

sure sounds good

**Comment by weilip1803** [comment]
Is this still being done? If it isnt is there an example of how I can serve static files from an upstream?

**Comment by htuch** [comment]
@weilip1803 you can do basic file serving with https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto#route-directresponseaction. This is not a full fledged web server. I think this thread captures current status, which is "help wanted".

**Comment by GNUGradyn** [comment]
I found this from an (older?) Envoy docs page. Is this module still maintained? https://jteso.github.io/envoy/documentation/site/modules/static/

**Comment by ghevge** [comment]
Was this functionality implemented or it is still work in progress ?  Thanks!

**Comment by YvesZHI** [comment]
So has Envoy supported this function?

**Comment by KBaichoo** [comment]
There's an additional feature in the work to provide custom error response based on if the upstream request errored: https://github.com/envoyproxy/envoy/issues/21441

**Comment by Spongman** [comment]
investigating nginx alternatives. Envoy looks promising but really surprised to find it can't serve static cocntent. shame.

**Comment by Jiehong** [comment]
@Spongman give a try to caddy instead

**Comment by ningyougang** [comment]
@Spongman 

I used below configuration to get local static page directly
```
static_resources:

  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          access_log:
          - name: envoy.access_loggers.stdout
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                direct_response:
                  status: 200
                  body:
                    filename: "/etc/envoy/hello-envoy.html"
```
